name: Waka Readme

on:
  # Trigger the workflow manually or on a schedule
  workflow_dispatch:
  schedule:
    # runs every 4 hours
    - cron: "0 */4 * * *"
  # Trigger the workflow on push events
  push:

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # This checks out your repository so the workflow can access your files
      - uses: athul/waka-readme@master # this action name
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_COMMIT: "TRUE"
          SHOW_DAYS_OF_WEEK: "TRUE"
          SHOW_LANGUAGE: "TRUE"
          SHOW_PROJECTS: "FALSE"
          SHOW_SHORT_INFO: "FALSE"
          SHOW_LOC_CHART: "FALSE"
